/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_umich_pyongjoo_QPSolver */

#ifndef _Included_edu_umich_pyongjoo_QPSolver
#define _Included_edu_umich_pyongjoo_QPSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_umich_pyongjoo_QPSolver
 * Method:    cvxopt_solve
 * Signature: ([D[D[D[D[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_umich_pyongjoo_QPSolver_cvxopt_1solve___3D_3D_3D_3D_3D_3D
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     edu_umich_pyongjoo_QPSolver
 * Method:    cvxopt_solve
 * Signature: ([D[D[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_umich_pyongjoo_QPSolver_cvxopt_1solve___3D_3D_3D_3D
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     edu_umich_pyongjoo_QPSolver
 * Method:    cvxopt_solve_sparse
 * Signature: ([D[I[I[D[D[I[I[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_umich_pyongjoo_QPSolver_cvxopt_1solve_1sparse
  (JNIEnv *, jobject, jdoubleArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jintArray, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
