SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2011 AND t.phonetic_code<11942 AND t.series_years<296 AND ci.role_id>2;,2727
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=20682 AND t.production_year>1993 AND t.series_years>644 AND ci.role_id=1;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11364 AND t.series_years<428 AND t.production_year=2009 AND ci.role_id<4;,29
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>850 AND t.production_year>2011 AND t.series_years>346 AND ci.role_id<2;,12036
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>17321 AND t.production_year=1964 AND t.series_years<767 AND ci.role_id>2;,156
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<474 AND t.production_year>1956 AND t.phonetic_code>14786 AND ci.role_id=2;,1010
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=10311 AND t.production_year<2008 AND t.series_years<988 AND ci.role_id>1;,34
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2013 AND t.series_years<842 AND t.phonetic_code=348 AND ci.role_id>1;,5
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2012 AND t.phonetic_code>14188 AND t.series_years=116 AND ci.role_id<2;,11
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=1109 AND t.phonetic_code<18964 AND t.production_year<2011 AND ci.role_id>1;,104
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=16804 AND t.series_years<351 AND t.production_year<2011 AND ci.role_id>1;,3
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=15862 AND t.series_years>1108 AND t.production_year<2001 AND ci.role_id>2;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<16641 AND t.production_year<1969 AND t.series_years>105 AND ci.role_id=2;,9913
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1974 AND t.phonetic_code<4570 AND t.series_years<554 AND ci.role_id>1;,7999
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<17498 AND t.production_year<2010 AND t.series_years>726 AND ci.role_id<4;,378740
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<16960 AND t.series_years>367 AND t.production_year<2009 AND ci.role_id<2;,192087
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>920 AND t.phonetic_code<22160 AND t.production_year=2011 AND ci.role_id>1;,24519
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1259 AND t.production_year>2012 AND t.phonetic_code>9675 AND ci.role_id=1;,1982
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=1082 AND t.production_year<2000 AND t.phonetic_code>12684 AND ci.role_id>1;,8
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1971 AND t.phonetic_code>16805 AND t.series_years<686 AND ci.role_id=2;,2494
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2005 AND t.phonetic_code>13138 AND t.series_years<448 AND ci.role_id=1;,70
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1949 AND t.phonetic_code<4840 AND t.series_years>593 AND ci.role_id>1;,163419
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=13420 AND t.production_year<2009 AND t.series_years>364 AND ci.role_id>4;,6
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<17810 AND t.production_year<2009 AND t.series_years>671 AND ci.role_id>2;,284050
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>340 AND t.phonetic_code>1758 AND t.production_year<2012 AND ci.role_id=2;,148269
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>663 AND t.production_year<1998 AND t.phonetic_code<1460 AND ci.role_id>2;,11327
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1965 AND t.series_years<294 AND t.phonetic_code>18065 AND ci.role_id>1;,17
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2007 AND t.series_years>328 AND t.phonetic_code>11932 AND ci.role_id=2;,11485
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<9598 AND t.series_years<545 AND t.production_year=2012 AND ci.role_id=1;,112
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2012 AND t.series_years<249 AND t.phonetic_code>17138 AND ci.role_id>1;,10
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1006 AND t.phonetic_code<20390 AND t.production_year<2010 AND ci.role_id=1;,169800
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<17612 AND t.series_years>704 AND t.production_year<1988 AND ci.role_id<2;,43754
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>159 AND t.production_year<2012 AND t.phonetic_code<14735 AND ci.role_id>1;,396249
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<16524 AND t.production_year=2001 AND t.series_years>1228 AND ci.role_id=1;,7500
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=5580 AND t.production_year<2003 AND t.series_years>603 AND ci.role_id=2;,34
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<480 AND t.production_year>2001 AND t.phonetic_code<12968 AND ci.role_id=4;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2001 AND t.series_years>451 AND t.phonetic_code>15754 AND ci.role_id<2;,29507
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>426 AND t.production_year>2012 AND t.phonetic_code<348 AND ci.role_id>1;,234
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2005 AND t.series_years>1145 AND t.phonetic_code>10256 AND ci.role_id>2;,90509
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>10256 AND t.series_years=523 AND t.production_year<2003 AND ci.role_id=2;,14
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<20698 AND t.production_year<2010 AND t.series_years>1088 AND ci.role_id=2;,104186
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11964 AND t.production_year=2004 AND t.series_years>762 AND ci.role_id=2;,4424
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<20345 AND t.production_year>1961 AND t.series_years<579 AND ci.role_id=2;,7414
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>3486 AND t.production_year<2006 AND t.series_years<690 AND ci.role_id=1;,23256
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>3222 AND t.series_years>1221 AND t.production_year<2006 AND ci.role_id=1;,66742
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>298 AND t.series_years<1078 AND t.production_year>2009 AND ci.role_id>1;,25
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<14735 AND t.production_year>1997 AND t.series_years>709 AND ci.role_id=1;,98239
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<6092 AND t.series_years>613 AND t.production_year=2006 AND ci.role_id>1;,9232
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11790 AND t.production_year<2002 AND t.series_years>503 AND ci.role_id=1;,89134
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<939 AND t.phonetic_code<11652 AND t.production_year>2002 AND ci.role_id<4;,158
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2007 AND t.phonetic_code>7311 AND t.series_years=1014 AND ci.role_id>1;,53
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1993 AND t.phonetic_code>14208 AND t.series_years=214 AND ci.role_id=1;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1957 AND t.series_years<764 AND t.phonetic_code<2692 AND ci.role_id=1;,1287
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1008 AND t.phonetic_code>6855 AND t.production_year<2012 AND ci.role_id<2;,46789
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<3900 AND t.production_year<2008 AND t.series_years<235 AND ci.role_id>1;,1165
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=1288 AND t.production_year<2006 AND t.phonetic_code<9645 AND ci.role_id>1;,35
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<910 AND t.phonetic_code=17060 AND t.production_year<2011 AND ci.role_id=1;,14
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>10389 AND t.series_years>524 AND t.production_year>1965 AND ci.role_id>2;,208320
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=1291 AND t.phonetic_code<2966 AND t.production_year>1957 AND ci.role_id=1;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<16025 AND t.series_years>303 AND t.production_year>1970 AND ci.role_id>4;,165208
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2005 AND t.series_years>965 AND t.phonetic_code<10521 AND ci.role_id=2;,21189
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<129 AND t.phonetic_code>2350 AND t.production_year>1955 AND ci.role_id=2;,84
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1988 AND t.phonetic_code>5342 AND t.series_years<881 AND ci.role_id>2;,28976
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<669 AND t.production_year<1989 AND t.phonetic_code>2367 AND ci.role_id=2;,13265
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2005 AND t.phonetic_code>1134 AND t.series_years<659 AND ci.role_id>2;,17
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>17146 AND t.production_year<2009 AND t.series_years<988 AND ci.role_id<2;,13961
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1048 AND t.phonetic_code>2687 AND t.production_year=1991 AND ci.role_id>1;,6
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>702 AND t.phonetic_code=10379 AND t.production_year<2004 AND ci.role_id>4;,22
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1279 AND t.production_year=2001 AND t.phonetic_code>2035 AND ci.role_id>1;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2012 AND t.series_years>353 AND t.phonetic_code<16651 AND ci.role_id>1;,430573
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>143 AND t.series_years<1103 AND t.production_year<2007 AND ci.role_id=2;,56364
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<20959 AND t.series_years>466 AND t.production_year=1974 AND ci.role_id=2;,1412
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<916 AND t.production_year<2010 AND t.phonetic_code>17634 AND ci.role_id>1;,11380
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2007 AND t.phonetic_code>17346 AND t.series_years>699 AND ci.role_id>1;,3743
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2010 AND t.series_years>592 AND t.phonetic_code>13291 AND ci.role_id>2;,17359
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<4483 AND t.production_year>1995 AND t.series_years>1273 AND ci.role_id>2;,73222
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1139 AND t.phonetic_code=5153 AND t.production_year=1993 AND ci.role_id>2;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=796 AND t.phonetic_code<6497 AND t.production_year<2012 AND ci.role_id>2;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<619 AND t.production_year>1958 AND t.phonetic_code<5060 AND ci.role_id>1;,7505
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>6981 AND t.series_years>839 AND t.production_year>1958 AND ci.role_id>1;,334328
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>166 AND t.production_year=2008 AND t.phonetic_code>12296 AND ci.role_id=1;,3571
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1989 AND t.phonetic_code>20591 AND t.series_years>171 AND ci.role_id<4;,215
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<9841 AND t.production_year<2007 AND t.series_years=1277 AND ci.role_id=1;,36
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2013 AND t.phonetic_code>3326 AND t.series_years>943 AND ci.role_id>1;,8723
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2010 AND t.series_years=125 AND t.phonetic_code>7340 AND ci.role_id>2;,13
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>14556 AND t.series_years<771 AND t.production_year=1970 AND ci.role_id>1;,702
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=8988 AND t.production_year<2009 AND t.series_years>1067 AND ci.role_id>4;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<503 AND t.production_year<1993 AND t.phonetic_code=16722 AND ci.role_id>1;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=14682 AND t.production_year<2007 AND t.series_years<836 AND ci.role_id=4;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>12248 AND t.production_year<2011 AND t.series_years<1193 AND ci.role_id=2;,27554
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>15732 AND t.production_year>1999 AND t.series_years>961 AND ci.role_id>2;,74283
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<19649 AND t.production_year<2012 AND t.series_years=191 AND ci.role_id=1;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2009 AND t.phonetic_code>14657 AND t.series_years<170 AND ci.role_id=1;,30
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2006 AND t.series_years=940 AND t.phonetic_code>3431 AND ci.role_id>1;,325
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<16926 AND t.series_years>709 AND t.production_year=2001 AND ci.role_id>1;,19760
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>11363 AND t.production_year<1970 AND t.series_years>563 AND ci.role_id=1;,2198
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1991 AND t.phonetic_code>11315 AND t.series_years<1020 AND ci.role_id<2;,228
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2006 AND t.series_years=969 AND t.phonetic_code>10 AND ci.role_id>2;,71
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>10435 AND t.series_years>1175 AND t.production_year<2004 AND ci.role_id>1;,96783
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1278 AND t.phonetic_code<14648 AND t.production_year<2005 AND ci.role_id>1;,92251
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<14655 AND t.series_years>559 AND t.production_year=2000 AND ci.role_id>1;,13889
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1988 AND t.series_years<1117 AND t.phonetic_code>7219 AND ci.role_id=4;,12281
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2012 AND t.phonetic_code<19556 AND t.series_years>805 AND ci.role_id>1;,476394
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1101 AND t.production_year>1952 AND t.phonetic_code<1624 AND ci.role_id<2;,19772
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1987 AND t.series_years>906 AND t.phonetic_code<16808 AND ci.role_id>1;,23723
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1974 AND t.phonetic_code>5758 AND t.series_years=940 AND ci.role_id<2;,185
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>1639 AND t.series_years>1245 AND t.production_year<2012 AND ci.role_id=1;,113833
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>256 AND t.phonetic_code<20514 AND t.production_year=1997 AND ci.role_id>1;,15547
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<939 AND t.phonetic_code>3469 AND t.production_year<1996 AND ci.role_id>1;,66601
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>1435 AND t.production_year<1984 AND t.series_years<375 AND ci.role_id=2;,3710
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>9852 AND t.series_years=895 AND t.production_year<2012 AND ci.role_id=1;,10
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<12968 AND t.production_year=2013 AND t.series_years>441 AND ci.role_id>2;,5762
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>7193 AND t.production_year=1963 AND t.series_years>194 AND ci.role_id=2;,319
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>371 AND t.phonetic_code<294 AND t.production_year<2013 AND ci.role_id>2;,7591
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2004 AND t.series_years>784 AND t.phonetic_code=16806 AND ci.role_id>1;,16
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=11377 AND t.series_years<1190 AND t.production_year<2006 AND ci.role_id<2;,23
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2006 AND t.series_years>179 AND t.phonetic_code=14528 AND ci.role_id=1;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<585 AND t.production_year>1999 AND t.phonetic_code<16706 AND ci.role_id=1;,182
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<175 AND t.production_year<1985 AND t.phonetic_code>310 AND ci.role_id=1;,2380
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2011 AND t.phonetic_code<7345 AND t.series_years>1178 AND ci.role_id=1;,5402
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=808 AND t.production_year<2009 AND t.phonetic_code>5929 AND ci.role_id>1;,17
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1134 AND t.phonetic_code<8110 AND t.production_year>2008 AND ci.role_id<2;,130
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>4625 AND t.production_year<2000 AND t.series_years>955 AND ci.role_id>1;,124930
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2005 AND t.series_years>533 AND t.phonetic_code<5239 AND ci.role_id<2;,54349
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2006 AND t.series_years<439 AND t.phonetic_code>19542 AND ci.role_id>1;,836
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1969 AND t.series_years>1038 AND t.phonetic_code<8998 AND ci.role_id=2;,57852
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1976 AND t.phonetic_code<17797 AND t.series_years<622 AND ci.role_id>2;,15103
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2012 AND t.phonetic_code<2602 AND t.series_years>902 AND ci.role_id=1;,1706
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<958 AND t.phonetic_code>13486 AND t.production_year>2008 AND ci.role_id>2;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1142 AND t.phonetic_code<8503 AND t.production_year>1992 AND ci.role_id=1;,303
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1980 AND t.phonetic_code>6276 AND t.series_years=1030 AND ci.role_id<2;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=4527 AND t.series_years<1147 AND t.production_year<1974 AND ci.role_id>1;,3
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>14408 AND t.production_year>1987 AND t.series_years<297 AND ci.role_id<2;,81
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1990 AND t.phonetic_code<16641 AND t.series_years<539 AND ci.role_id>1;,118
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>719 AND t.phonetic_code>8112 AND t.production_year>2012 AND ci.role_id=1;,2157
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>20823 AND t.series_years>659 AND t.production_year>1955 AND ci.role_id=2;,5275
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<3696 AND t.series_years>1266 AND t.production_year>2008 AND ci.role_id=1;,8466
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>17158 AND t.production_year<2011 AND t.series_years>990 AND ci.role_id>2;,54039
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1996 AND t.series_years=1239 AND t.phonetic_code>5034 AND ci.role_id=1;,158
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>4775 AND t.series_years>672 AND t.production_year>2002 AND ci.role_id>2;,150235
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>224 AND t.production_year>2009 AND t.phonetic_code=3072 AND ci.role_id>2;,72
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>15651 AND t.series_years>323 AND t.production_year=1958 AND ci.role_id>1;,77
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1228 AND t.production_year>2006 AND t.phonetic_code>16804 AND ci.role_id>2;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2007 AND t.phonetic_code>3428 AND t.series_years<333 AND ci.role_id>1;,21
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2013 AND t.phonetic_code=2547 AND t.series_years>126 AND ci.role_id=1;,192
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1961 AND t.phonetic_code>6245 AND t.series_years<437 AND ci.role_id=1;,949
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=14160 AND t.production_year<2000 AND t.series_years<1053 AND ci.role_id=4;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1993 AND t.phonetic_code<20328 AND t.series_years<526 AND ci.role_id>1;,20997
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1964 AND t.series_years>143 AND t.phonetic_code=761 AND ci.role_id=1;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<813 AND t.production_year>2002 AND t.phonetic_code<7336 AND ci.role_id<2;,131
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>656 AND t.production_year<2010 AND t.phonetic_code>4392 AND ci.role_id>1;,355468
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=562 AND t.production_year<2005 AND t.phonetic_code<11365 AND ci.role_id>1;,5
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1968 AND t.series_years<1237 AND t.phonetic_code>10547 AND ci.role_id>1;,97496
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>5892 AND t.series_years>1220 AND t.production_year>2004 AND ci.role_id<2;,50391
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<762 AND t.production_year>2010 AND t.phonetic_code>8829 AND ci.role_id=1;,70
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>241 AND t.phonetic_code=18960 AND t.production_year=2011 AND ci.role_id>1;,38
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1999 AND t.phonetic_code>6257 AND t.series_years>633 AND ci.role_id=2;,55120
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<3199 AND t.series_years<128 AND t.production_year<1970 AND ci.role_id>2;,160
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1976 AND t.series_years>153 AND t.phonetic_code>17575 AND ci.role_id=2;,216
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2009 AND t.phonetic_code<5244 AND t.series_years>542 AND ci.role_id=1;,65841
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<20686 AND t.series_years>282 AND t.production_year<1960 AND ci.role_id=1;,2566
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2005 AND t.phonetic_code<3696 AND t.series_years<553 AND ci.role_id>1;,8
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=12193 AND t.production_year<2012 AND t.series_years>100 AND ci.role_id=1;,34
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1997 AND t.phonetic_code<11135 AND t.series_years<879 AND ci.role_id>4;,11133
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<5555 AND t.production_year>2002 AND t.series_years<655 AND ci.role_id>1;,9
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2008 AND t.phonetic_code>20811 AND t.series_years>670 AND ci.role_id>1;,688
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11763 AND t.series_years=1086 AND t.production_year<2009 AND ci.role_id=1;,27
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1995 AND t.series_years>922 AND t.phonetic_code<5517 AND ci.role_id=1;,48302
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2010 AND t.series_years>752 AND t.phonetic_code<16037 AND ci.role_id=2;,10313
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<16821 AND t.production_year<1998 AND t.series_years>732 AND ci.role_id=4;,21465
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=8979 AND t.series_years>127 AND t.production_year>1970 AND ci.role_id>2;,6
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<17236 AND t.production_year<2011 AND t.series_years<128 AND ci.role_id>1;,1185
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>614 AND t.phonetic_code>17009 AND t.production_year<2012 AND ci.role_id<2;,46492
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2006 AND t.series_years<550 AND t.phonetic_code<239 AND ci.role_id<2;,727
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2008 AND t.series_years=1060 AND t.phonetic_code<1844 AND ci.role_id<4;,77
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>16061 AND t.series_years<230 AND t.production_year>1994 AND ci.role_id>1;,14
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1998 AND t.series_years>707 AND t.phonetic_code>794 AND ci.role_id=2;,83375
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2012 AND t.series_years>1126 AND t.phonetic_code<10185 AND ci.role_id>2;,4565
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1179 AND t.production_year>1956 AND t.phonetic_code=9945 AND ci.role_id<2;,16
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<810 AND t.phonetic_code<5580 AND t.production_year>2002 AND ci.role_id=1;,88
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>130 AND t.production_year>2011 AND t.phonetic_code>71 AND ci.role_id>1;,37488
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<837 AND t.series_years>849 AND t.production_year=2010 AND ci.role_id>1;,1246
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1215 AND t.production_year<1990 AND t.phonetic_code>16706 AND ci.role_id=1;,21692
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<314 AND t.production_year=1993 AND t.phonetic_code<2816 AND ci.role_id=1;,43
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1993 AND t.phonetic_code<18237 AND t.series_years>335 AND ci.role_id=1;,91084
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>14447 AND t.production_year>2010 AND t.series_years>887 AND ci.role_id<2;,6292
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11922 AND t.production_year=2007 AND t.series_years<993 AND ci.role_id>2;,5
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2007 AND t.series_years>902 AND t.phonetic_code>20591 AND ci.role_id>1;,5071
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=11399 AND t.production_year<2011 AND t.series_years>618 AND ci.role_id=4;,8
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>924 AND t.phonetic_code>17172 AND t.production_year<2004 AND ci.role_id<2;,23345
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>3471 AND t.production_year>1999 AND t.series_years>517 AND ci.role_id=1;,96408
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<3623 AND t.series_years>1117 AND t.production_year>2011 AND ci.role_id>1;,9811
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>1804 AND t.production_year<2008 AND t.series_years=124 AND ci.role_id=2;,9
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>7063 AND t.series_years=603 AND t.production_year<2010 AND ci.role_id=2;,24
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<18304 AND t.series_years>1103 AND t.production_year<2012 AND ci.role_id=1;,153841
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>901 AND t.phonetic_code<1515 AND t.production_year>2012 AND ci.role_id=1;,439
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2010 AND t.phonetic_code<3895 AND t.series_years>286 AND ci.role_id>4;,49868
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2007 AND t.series_years>1156 AND t.phonetic_code=13156 AND ci.role_id>1;,7
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2009 AND t.phonetic_code>6715 AND t.series_years<1223 AND ci.role_id<4;,120
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<947 AND t.production_year<2010 AND t.phonetic_code=7051 AND ci.role_id<2;,13
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>17319 AND t.production_year=2009 AND t.series_years>941 AND ci.role_id=2;,872
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<5364 AND t.series_years>593 AND t.production_year<1999 AND ci.role_id=2;,23818
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<707 AND t.phonetic_code=17185 AND t.production_year<2009 AND ci.role_id>1;,12
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>857 AND t.production_year=2010 AND t.phonetic_code>6782 AND ci.role_id>1;,13537
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<106 AND t.production_year>1995 AND t.phonetic_code<9347 AND ci.role_id>2;,9
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=16031 AND t.series_years>187 AND t.production_year<1992 AND ci.role_id>2;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1954 AND t.series_years>182 AND t.phonetic_code<10614 AND ci.role_id=1;,140574
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=10439 AND t.series_years<982 AND t.production_year<1988 AND ci.role_id=1;,17
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2004 AND t.series_years>431 AND t.phonetic_code>16372 AND ci.role_id=2;,1964
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2005 AND t.series_years<961 AND t.phonetic_code<17215 AND ci.role_id>4;,13
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<18305 AND t.production_year=1985 AND t.series_years<772 AND ci.role_id=1;,133
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>4452 AND t.production_year<1994 AND t.series_years<985 AND ci.role_id=1;,51647
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2011 AND t.phonetic_code<13984 AND t.series_years>1071 AND ci.role_id>2;,19752
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<14575 AND t.series_years>636 AND t.production_year>1953 AND ci.role_id>2;,277340
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>13485 AND t.production_year<2011 AND t.series_years=726 AND ci.role_id>1;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1013 AND t.phonetic_code=17321 AND t.production_year<2006 AND ci.role_id>1;,12
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2009 AND t.series_years>733 AND t.phonetic_code=6203 AND ci.role_id<2;,3
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<3486 AND t.series_years<1262 AND t.production_year=2001 AND ci.role_id>1;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<303 AND t.production_year<1970 AND t.phonetic_code<16274 AND ci.role_id>4;,1238
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2012 AND t.phonetic_code<18280 AND t.series_years<730 AND ci.role_id<2;,152
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=3635 AND t.production_year<2007 AND t.series_years>1011 AND ci.role_id<4;,153
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<18335 AND t.production_year<2007 AND t.series_years=1186 AND ci.role_id<2;,22
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=260 AND t.phonetic_code<10389 AND t.production_year<2011 AND ci.role_id=2;,15
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1955 AND t.series_years>212 AND t.phonetic_code<2495 AND ci.role_id>2;,69264
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2009 AND t.series_years>494 AND t.phonetic_code<3632 AND ci.role_id>1;,116486
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>163 AND t.phonetic_code<2690 AND t.production_year>2009 AND ci.role_id>1;,15696
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2012 AND t.series_years<132 AND t.phonetic_code>1767 AND ci.role_id>2;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2007 AND t.phonetic_code<6675 AND t.series_years>535 AND ci.role_id=2;,1961
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1954 AND t.series_years>886 AND t.phonetic_code>6250 AND ci.role_id=1;,150069
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1964 AND t.phonetic_code<17789 AND t.series_years>1078 AND ci.role_id>1;,422608
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>2978 AND t.series_years>1220 AND t.production_year<2012 AND ci.role_id=1;,109707
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>12021 AND t.series_years<784 AND t.production_year>1959 AND ci.role_id=2;,7821
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>2236 AND t.series_years>1058 AND t.production_year>2010 AND ci.role_id=1;,17390
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>2599 AND t.series_years<228 AND t.production_year>1956 AND ci.role_id=1;,352
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2009 AND t.phonetic_code<21712 AND t.series_years=1149 AND ci.role_id=2;,124
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<1513 AND t.series_years>379 AND t.production_year>1999 AND ci.role_id>1;,35053
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2012 AND t.phonetic_code>14216 AND t.series_years<608 AND ci.role_id=2;,3884
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<662 AND t.phonetic_code>22941 AND t.production_year<1990 AND ci.role_id=1;,47
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2006 AND t.phonetic_code<10340 AND t.series_years>349 AND ci.role_id>2;,56409
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1160 AND t.production_year<2012 AND t.phonetic_code=19415 AND ci.role_id>2;,13
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>4933 AND t.series_years<963 AND t.production_year=1962 AND ci.role_id>2;,545
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2011 AND t.phonetic_code<2536 AND t.series_years>1140 AND ci.role_id<2;,24580
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>280 AND t.production_year<1984 AND t.series_years=898 AND ci.role_id=1;,3
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2012 AND t.phonetic_code<15054 AND t.series_years>1211 AND ci.role_id=1;,3046
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2013 AND t.series_years<1043 AND t.phonetic_code<9 AND ci.role_id=1;,33
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<15823 AND t.series_years=976 AND t.production_year<2013 AND ci.role_id=2;,13
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>837 AND t.phonetic_code>136 AND t.production_year<2000 AND ci.role_id>2;,128772
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1972 AND t.series_years<100 AND t.phonetic_code>17268 AND ci.role_id>1;,26
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2008 AND t.phonetic_code=7177 AND t.series_years>513 AND ci.role_id=2;,40
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=6706 AND t.production_year<2009 AND t.series_years<658 AND ci.role_id<2;,5
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1072 AND t.phonetic_code=14556 AND t.production_year<2009 AND ci.role_id=1;,23
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>1263 AND t.series_years=1106 AND t.production_year<2012 AND ci.role_id>1;,330
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2001 AND t.phonetic_code<20961 AND t.series_years>927 AND ci.role_id=1;,102149
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=765 AND t.production_year<2008 AND t.phonetic_code>6772 AND ci.role_id=1;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1999 AND t.series_years>1044 AND t.phonetic_code>19707 AND ci.role_id>2;,4853
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=10423 AND t.production_year=2004 AND t.series_years>271 AND ci.role_id>4;,46
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1160 AND t.phonetic_code=20328 AND t.production_year<2012 AND ci.role_id>1;,93
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1041 AND t.phonetic_code<14222 AND t.production_year>2002 AND ci.role_id>4;,12
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<14728 AND t.production_year<2009 AND t.series_years<298 AND ci.role_id=2;,2441
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>7639 AND t.production_year<2009 AND t.series_years<917 AND ci.role_id=2;,20065
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1044 AND t.phonetic_code>14696 AND t.production_year>2011 AND ci.role_id>1;,13
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>625 AND t.phonetic_code<915 AND t.production_year<2002 AND ci.role_id=2;,6953
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2000 AND t.series_years<736 AND t.phonetic_code<5327 AND ci.role_id=1;,82
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>385 AND t.phonetic_code>8196 AND t.production_year<2011 AND ci.role_id=2;,93345
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>19600 AND t.series_years>347 AND t.production_year>1980 AND ci.role_id=2;,9336
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>1491 AND t.series_years>584 AND t.production_year<2006 AND ci.role_id>2;,246810
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1137 AND t.production_year>2004 AND t.phonetic_code<7960 AND ci.role_id=1;,30342
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1993 AND t.series_years<582 AND t.phonetic_code>13138 AND ci.role_id=1;,113
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=326 AND t.production_year<1986 AND t.phonetic_code>1263 AND ci.role_id>1;,49
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=510 AND t.production_year>2010 AND t.series_years>696 AND ci.role_id>2;,23
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>12348 AND t.production_year>2009 AND t.series_years<592 AND ci.role_id=2;,11
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>11952 AND t.production_year<1965 AND t.series_years<201 AND ci.role_id>1;,1378
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2012 AND t.series_years>791 AND t.phonetic_code<8408 AND ci.role_id>2;,4156
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>981 AND t.phonetic_code>1305 AND t.production_year<2010 AND ci.role_id=2;,109644
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>13087 AND t.series_years<1263 AND t.production_year>2003 AND ci.role_id=1;,79
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1236 AND t.phonetic_code>16694 AND t.production_year>2007 AND ci.role_id>1;,10
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<2072 AND t.production_year>1993 AND t.series_years>178 AND ci.role_id>2;,44716
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<2842 AND t.production_year=2009 AND t.series_years>870 AND ci.role_id<2;,1426
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<118 AND t.phonetic_code<7805 AND t.production_year<2011 AND ci.role_id=1;,336
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2004 AND t.series_years=689 AND t.phonetic_code>3947 AND ci.role_id=2;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<558 AND t.production_year>1969 AND t.phonetic_code>10837 AND ci.role_id>2;,117
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<250 AND t.production_year<2003 AND t.phonetic_code>10615 AND ci.role_id>2;,1498
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>718 AND t.phonetic_code>19718 AND t.production_year=2011 AND ci.role_id=1;,590
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1985 AND t.phonetic_code<1598 AND t.series_years>501 AND ci.role_id>2;,4386
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2012 AND t.phonetic_code>3450 AND t.series_years>473 AND ci.role_id>1;,19219
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>3957 AND t.production_year=2005 AND t.series_years>330 AND ci.role_id=2;,5475
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1992 AND t.series_years>337 AND t.phonetic_code=14130 AND ci.role_id=1;,18
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<638 AND t.phonetic_code<19619 AND t.production_year<1961 AND ci.role_id>4;,2483
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1206 AND t.phonetic_code<16700 AND t.production_year=1974 AND ci.role_id=1;,2178
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1996 AND t.phonetic_code=2684 AND t.series_years>448 AND ci.role_id>1;,39
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2004 AND t.series_years>785 AND t.phonetic_code<348 AND ci.role_id>2;,630
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<7318 AND t.series_years>562 AND t.production_year>2005 AND ci.role_id>1;,70971
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2005 AND t.series_years>456 AND t.phonetic_code<2891 AND ci.role_id=1;,2118
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=655 AND t.phonetic_code>16804 AND t.production_year<1989 AND ci.role_id<4;,33
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>497 AND t.production_year=2012 AND t.phonetic_code<2783 AND ci.role_id>1;,5462
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1991 AND t.series_years<1084 AND t.phonetic_code<1582 AND ci.role_id>2;,38
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1992 AND t.series_years<1118 AND t.phonetic_code<16905 AND ci.role_id=2;,61
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2010 AND t.series_years<556 AND t.phonetic_code<4049 AND ci.role_id<2;,79
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<17007 AND t.production_year<2001 AND t.series_years<556 AND ci.role_id>2;,11461
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>798 AND t.production_year=2006 AND t.phonetic_code>15896 AND ci.role_id<2;,2749
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<5743 AND t.series_years<1112 AND t.production_year<1990 AND ci.role_id=1;,30756
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>1094 AND t.series_years>1132 AND t.production_year>2008 AND ci.role_id<2;,33380
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<3188 AND t.production_year>2006 AND t.series_years<1258 AND ci.role_id<2;,76
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=2723 AND t.production_year<2006 AND t.series_years>857 AND ci.role_id>1;,52
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2008 AND t.phonetic_code>5119 AND t.series_years<124 AND ci.role_id>4;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<318 AND t.phonetic_code>1845 AND t.production_year>2011 AND ci.role_id=1;,145
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1970 AND t.phonetic_code>14401 AND t.series_years<1291 AND ci.role_id<2;,7219
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2002 AND t.phonetic_code>12304 AND t.series_years<1048 AND ci.role_id>1;,44637
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>856 AND t.production_year=2000 AND t.phonetic_code<20545 AND ci.role_id=1;,8013
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<424 AND t.phonetic_code<19733 AND t.production_year=2012 AND ci.role_id=2;,19
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<10117 AND t.series_years<575 AND t.production_year=2012 AND ci.role_id>4;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>553 AND t.series_years=602 AND t.production_year<2011 AND ci.role_id>2;,28
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>416 AND t.production_year=1984 AND t.phonetic_code>12702 AND ci.role_id<2;,2002
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>11932 AND t.production_year<2000 AND t.series_years<1250 AND ci.role_id>4;,31930
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2011 AND t.series_years<659 AND t.phonetic_code>17011 AND ci.role_id=2;,9
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11515 AND t.production_year<2007 AND t.series_years>1172 AND ci.role_id=2;,43544
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1997 AND t.series_years>1139 AND t.phonetic_code<13875 AND ci.role_id<2;,18468
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1981 AND t.series_years>160 AND t.phonetic_code<16687 AND ci.role_id>4;,1051
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>4415 AND t.series_years<210 AND t.production_year>2006 AND ci.role_id=1;,45
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<18359 AND t.series_years<1192 AND t.production_year>1965 AND ci.role_id<2;,93933
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<17319 AND t.series_years>465 AND t.production_year>1996 AND ci.role_id>1;,337853
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1278 AND t.phonetic_code<7051 AND t.production_year>1992 AND ci.role_id<2;,46468
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2007 AND t.phonetic_code=20825 AND t.series_years>1131 AND ci.role_id>1;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2012 AND t.series_years<1156 AND t.phonetic_code=16253 AND ci.role_id<4;,97
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<2842 AND t.series_years>205 AND t.production_year=2001 AND ci.role_id>1;,5418
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1974 AND t.phonetic_code<16816 AND t.series_years>1236 AND ci.role_id=2;,75965
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2012 AND t.phonetic_code<834 AND t.series_years>876 AND ci.role_id>1;,1488
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<9007 AND t.series_years>942 AND t.production_year=2012 AND ci.role_id=1;,4116
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2005 AND t.series_years>130 AND t.phonetic_code>6092 AND ci.role_id=1;,137406
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>14081 AND t.production_year<2009 AND t.series_years<247 AND ci.role_id=1;,1515
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>784 AND t.phonetic_code<17811 AND t.production_year>1989 AND ci.role_id<2;,163112
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2006 AND t.phonetic_code>16081 AND t.series_years<1253 AND ci.role_id=1;,30
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>580 AND t.phonetic_code>2576 AND t.production_year=2012 AND ci.role_id>1;,20572
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2010 AND t.phonetic_code=3486 AND t.series_years<800 AND ci.role_id>4;,12
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1955 AND t.phonetic_code<2599 AND t.series_years<179 AND ci.role_id=2;,37
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>785 AND t.production_year=2010 AND t.phonetic_code=2128 AND ci.role_id=1;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>994 AND t.phonetic_code=11766 AND t.production_year>2011 AND ci.role_id>1;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2011 AND t.series_years<1297 AND t.phonetic_code<10436 AND ci.role_id=2;,8
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<2523 AND t.production_year<1985 AND t.series_years<244 AND ci.role_id>1;,903
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1159 AND t.production_year<2005 AND t.phonetic_code<16971 AND ci.role_id=1;,80197
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>783 AND t.production_year>1995 AND t.phonetic_code=17209 AND ci.role_id=1;,11
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=14409 AND t.series_years>423 AND t.production_year=2013 AND ci.role_id>1;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>6948 AND t.production_year>2008 AND t.series_years<1257 AND ci.role_id=1;,116
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<2978 AND t.series_years>829 AND t.production_year>1998 AND ci.role_id=2;,17779
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2011 AND t.series_years>587 AND t.phonetic_code>14696 AND ci.role_id>2;,8420
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1966 AND t.series_years<1145 AND t.phonetic_code>20961 AND ci.role_id>2;,204
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<20026 AND t.production_year<1995 AND t.series_years<699 AND ci.role_id=1;,30674
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2010 AND t.phonetic_code<11547 AND t.series_years>976 AND ci.role_id=1;,12076
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>17215 AND t.production_year=1965 AND t.series_years>156 AND ci.role_id=1;,341
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1996 AND t.phonetic_code<5342 AND t.series_years<119 AND ci.role_id=1;,245
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>671 AND t.production_year>2008 AND t.phonetic_code<1144 AND ci.role_id>1;,7633
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>13089 AND t.series_years<1200 AND t.production_year<2004 AND ci.role_id>1;,66613
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<6934 AND t.series_years>424 AND t.production_year>1996 AND ci.role_id>2;,116327
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<797 AND t.phonetic_code>2890 AND t.production_year=1985 AND ci.role_id=2;,23
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2010 AND t.series_years<228 AND t.phonetic_code<5555 AND ci.role_id<2;,1252
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2012 AND t.series_years=694 AND t.phonetic_code>12264 AND ci.role_id<2;,21
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>671 AND t.phonetic_code<20186 AND t.production_year<2008 AND ci.role_id=1;,197411
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=12288 AND t.production_year>1975 AND t.series_years<1019 AND ci.role_id>1;,3
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<267 AND t.production_year<1988 AND t.phonetic_code<13925 AND ci.role_id<2;,3257
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1964 AND t.series_years>320 AND t.phonetic_code>16905 AND ci.role_id<2;,447
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<510 AND t.series_years>894 AND t.production_year>1998 AND ci.role_id>1;,11020
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<2498 AND t.series_years<489 AND t.production_year>1991 AND ci.role_id=1;,62
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>247 AND t.production_year=1999 AND t.phonetic_code>6169 AND ci.role_id=2;,3588
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=10359 AND t.series_years>912 AND t.production_year>1987 AND ci.role_id>1;,200
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=241 AND t.phonetic_code<17575 AND t.production_year>1979 AND ci.role_id=1;,40
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2005 AND t.series_years<982 AND t.phonetic_code<19868 AND ci.role_id<2;,67915
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=464 AND t.phonetic_code<17011 AND t.production_year<2010 AND ci.role_id<2;,8
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2011 AND t.series_years>1000 AND t.phonetic_code<8989 AND ci.role_id>1;,11117
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1229 AND t.phonetic_code<14160 AND t.production_year<2005 AND ci.role_id=2;,54030
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1971 AND t.series_years<1261 AND t.phonetic_code=1282 AND ci.role_id>1;,175
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2010 AND t.phonetic_code>17319 AND t.series_years>689 AND ci.role_id=1;,36388
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<936 AND t.production_year>1995 AND t.phonetic_code<5060 AND ci.role_id=2;,7
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>1717 AND t.series_years>259 AND t.production_year=1995 AND ci.role_id=1;,5951
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1058 AND t.production_year=2007 AND t.phonetic_code>1847 AND ci.role_id<2;,3
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>17810 AND t.production_year=1983 AND t.series_years>489 AND ci.role_id<2;,404
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=2690 AND t.series_years<1038 AND t.production_year<1985 AND ci.role_id>2;,26
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<330 AND t.phonetic_code>1460 AND t.production_year<1958 AND ci.role_id>4;,1547
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2011 AND t.phonetic_code>6218 AND t.series_years>1249 AND ci.role_id=1;,5244
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1995 AND t.series_years>118 AND t.phonetic_code<16293 AND ci.role_id=2;,79166
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<256 AND t.production_year>1991 AND t.phonetic_code<7140 AND ci.role_id=4;,11
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=12460 AND t.series_years>1263 AND t.production_year<2009 AND ci.role_id=1;,23
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>14528 AND t.production_year<1954 AND t.series_years>209 AND ci.role_id=1;,8
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<785 AND t.phonetic_code>16884 AND t.production_year>1990 AND ci.role_id>4;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2008 AND t.series_years>1183 AND t.phonetic_code>19733 AND ci.role_id<2;,497
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>858 AND t.phonetic_code>9920 AND t.production_year=1994 AND ci.role_id>2;,3841
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=1025 AND t.production_year<2006 AND t.phonetic_code<9087 AND ci.role_id=1;,21
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2007 AND t.series_years>332 AND t.phonetic_code>6249 AND ci.role_id>1;,292495
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>13564 AND t.series_years>1282 AND t.production_year>1960 AND ci.role_id>4;,48191
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>18956 AND t.production_year<1991 AND t.series_years=1106 AND ci.role_id>1;,5
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<14648 AND t.series_years<377 AND t.production_year<1980 AND ci.role_id=2;,3064
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2011 AND t.phonetic_code>523 AND t.series_years>497 AND ci.role_id>2;,19051
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<465 AND t.production_year>1993 AND t.phonetic_code<6237 AND ci.role_id>1;,45
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=16670 AND t.production_year>2004 AND t.series_years>736 AND ci.role_id=1;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11784 AND t.series_years>1064 AND t.production_year<2006 AND ci.role_id>2;,125580
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>14687 AND t.production_year=2005 AND t.series_years>1193 AND ci.role_id=1;,3207
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<358 AND t.phonetic_code>1152 AND t.production_year<2005 AND ci.role_id=1;,6986
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>20825 AND t.production_year=1969 AND t.series_years<842 AND ci.role_id>2;,77
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1269 AND t.phonetic_code<17209 AND t.production_year>2010 AND ci.role_id>2;,41214
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<2537 AND t.series_years>320 AND t.production_year<1992 AND ci.role_id<2;,16281
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<996 AND t.production_year>2006 AND t.phonetic_code>6979 AND ci.role_id<2;,117
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2008 AND t.phonetic_code>11790 AND t.series_years<1131 AND ci.role_id>1;,63033
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>773 AND t.production_year=2001 AND t.phonetic_code>2283 AND ci.role_id<2;,8288
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=5517 AND t.series_years>131 AND t.production_year<1988 AND ci.role_id>1;,13
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<6492 AND t.series_years>313 AND t.production_year<1994 AND ci.role_id=1;,39062
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<12325 AND t.series_years>1127 AND t.production_year>2005 AND ci.role_id=4;,14599
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>659 AND t.phonetic_code>5364 AND t.production_year>2002 AND ci.role_id>1;,189807
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1993 AND t.phonetic_code>22192 AND t.series_years>566 AND ci.role_id>1;,4393
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=5478 AND t.series_years>984 AND t.production_year<2005 AND ci.role_id=1;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=16864 AND t.production_year<2010 AND t.series_years>575 AND ci.role_id>4;,46
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<713 AND t.phonetic_code<16657 AND t.production_year<1972 AND ci.role_id>2;,15548
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1991 AND t.series_years=1148 AND t.phonetic_code<13316 AND ci.role_id=1;,146
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1956 AND t.phonetic_code>1267 AND t.series_years<1022 AND ci.role_id=2;,417
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2005 AND t.phonetic_code<11652 AND t.series_years<1042 AND ci.role_id>2;,37269
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<317 AND t.phonetic_code<6360 AND t.production_year<2011 AND ci.role_id=1;,2879
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>293 AND t.production_year>2011 AND t.phonetic_code<5779 AND ci.role_id>2;,10195
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11723 AND t.series_years>529 AND t.production_year>2007 AND ci.role_id<2;,25418
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<7637 AND t.production_year>1994 AND t.series_years>477 AND ci.role_id<4;,146007
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2004 AND t.phonetic_code=4857 AND t.series_years<1262 AND ci.role_id=1;,52
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<4227 AND t.series_years>567 AND t.production_year<1994 AND ci.role_id=2;,14676
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=1288 AND t.phonetic_code>17141 AND t.production_year>1984 AND ci.role_id>4;,15
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1987 AND t.series_years>638 AND t.phonetic_code>14401 AND ci.role_id>2;,1339
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1175 AND t.phonetic_code>1484 AND t.production_year<2008 AND ci.role_id=2;,60731
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<242 AND t.production_year>2007 AND t.phonetic_code>525 AND ci.role_id>1;,26
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2010 AND t.phonetic_code<17720 AND t.series_years=629 AND ci.role_id=1;,33
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1970 AND t.series_years>997 AND t.phonetic_code>3060 AND ci.role_id>2;,288814
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1985 AND t.series_years>719 AND t.phonetic_code<1100 AND ci.role_id=1;,13896
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1292 AND t.phonetic_code=1109 AND t.production_year<2010 AND ci.role_id>1;,11
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<11327 AND t.series_years<402 AND t.production_year<2003 AND ci.role_id>2;,3988
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>557 AND t.phonetic_code<16822 AND t.production_year<2011 AND ci.role_id=1;,190534
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>510 AND t.production_year<1995 AND t.phonetic_code>16612 AND ci.role_id<2;,25338
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<173 AND t.phonetic_code>16955 AND t.production_year<2007 AND ci.role_id>1;,724
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<670 AND t.production_year=2007 AND t.series_years>305 AND ci.role_id<2;,307
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>6203 AND t.series_years>1008 AND t.production_year=2004 AND ci.role_id>1;,21646
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2003 AND t.series_years=909 AND t.phonetic_code<19733 AND ci.role_id=4;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<907 AND t.production_year>2004 AND t.phonetic_code>8521 AND ci.role_id>2;,11
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2008 AND t.phonetic_code=18273 AND t.series_years>599 AND ci.role_id=1;,3
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1984 AND t.series_years>773 AND t.phonetic_code<2782 AND ci.role_id<2;,753
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1999 AND t.series_years<1062 AND t.phonetic_code<6735 AND ci.role_id=2;,19998
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=447 AND t.phonetic_code<2332 AND t.production_year<1964 AND ci.role_id>1;,12
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>7362 AND t.series_years>998 AND t.production_year>2002 AND ci.role_id>1;,162850
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2010 AND t.phonetic_code>2334 AND t.series_years<140 AND ci.role_id>1;,15
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<19420 AND t.production_year>2009 AND t.series_years<955 AND ci.role_id>1;,25
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>7197 AND t.series_years>199 AND t.production_year<2001 AND ci.role_id>1;,168117
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>602 AND t.production_year=2012 AND t.phonetic_code<11515 AND ci.role_id=1;,5179
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1105 AND t.production_year>2010 AND t.phonetic_code<1995 AND ci.role_id=1;,2924
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1990 AND t.phonetic_code<11784 AND t.series_years>926 AND ci.role_id=2;,10078
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2012 AND t.phonetic_code>18261 AND t.series_years>566 AND ci.role_id>2;,1008
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>482 AND t.production_year<2011 AND t.phonetic_code>17705 AND ci.role_id>1;,68995
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1137 AND t.phonetic_code>10436 AND t.production_year=2003 AND ci.role_id=1;,4747
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2011 AND t.phonetic_code<11750 AND t.series_years>1014 AND ci.role_id>1;,22443
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1960 AND t.phonetic_code<8058 AND t.series_years>224 AND ci.role_id=2;,72854
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2012 AND t.phonetic_code>16700 AND t.series_years>472 AND ci.role_id>2;,1936
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<3906 AND t.series_years<1036 AND t.production_year=2012 AND ci.role_id=1;,78
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<910 AND t.phonetic_code>71 AND t.production_year>2009 AND ci.role_id<2;,183
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1990 AND t.phonetic_code<8509 AND t.series_years<1156 AND ci.role_id<2;,40675
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>620 AND t.phonetic_code>6979 AND t.production_year<2012 AND ci.role_id>1;,332194
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>15782 AND t.production_year<2011 AND t.series_years<761 AND ci.role_id>1;,13577
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>14122 AND t.production_year=2006 AND t.series_years>186 AND ci.role_id=4;,1092
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=17858 AND t.series_years>538 AND t.production_year<1997 AND ci.role_id>1;,20
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2007 AND t.phonetic_code>16773 AND t.series_years>452 AND ci.role_id=1;,47376
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<10 AND t.production_year<2011 AND t.series_years<210 AND ci.role_id=2;,5
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>10555 AND t.series_years<604 AND t.production_year>2004 AND ci.role_id>1;,13
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>621 AND t.phonetic_code<6683 AND t.production_year>2004 AND ci.role_id>1;,77199
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1993 AND t.phonetic_code>8113 AND t.series_years<847 AND ci.role_id<2;,131
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>7042 AND t.production_year>1984 AND t.series_years>996 AND ci.role_id=1;,128610
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2012 AND t.series_years>944 AND t.phonetic_code>10371 AND ci.role_id>1;,5859
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>5171 AND t.production_year<1959 AND t.series_years<434 AND ci.role_id=4;,1203
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<10274 AND t.production_year>2010 AND t.series_years>1118 AND ci.role_id>1;,31104
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2012 AND t.series_years>440 AND t.phonetic_code<14651 AND ci.role_id=2;,3990
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2009 AND t.phonetic_code<10114 AND t.series_years>685 AND ci.role_id=2;,8948
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>621 AND t.series_years=690 AND t.production_year<1998 AND ci.role_id<4;,6
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1995 AND t.series_years>358 AND t.phonetic_code=8992 AND ci.role_id>2;,33
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2010 AND t.series_years<1008 AND t.phonetic_code>11723 AND ci.role_id=2;,18435
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<623 AND t.phonetic_code>13603 AND t.production_year>1969 AND ci.role_id=2;,44
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2008 AND t.series_years<1270 AND t.phonetic_code=1091 AND ci.role_id>1;,24
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1997 AND t.series_years>753 AND t.phonetic_code=2991 AND ci.role_id>1;,61
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1996 AND t.phonetic_code=11515 AND t.series_years>701 AND ci.role_id=1;,11
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2011 AND t.phonetic_code>15758 AND t.series_years<422 AND ci.role_id>2;,1
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=19290 AND t.series_years>1021 AND t.production_year>1960 AND ci.role_id=1;,5
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=14546 AND t.series_years>740 AND t.production_year=1999 AND ci.role_id>2;,11
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2013 AND t.series_years=1149 AND t.phonetic_code<644 AND ci.role_id>2;,14
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<6250 AND t.production_year>2010 AND t.series_years>1162 AND ci.role_id=2;,4766
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2011 AND t.series_years>1230 AND t.phonetic_code>13106 AND ci.role_id<2;,4240
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<9914 AND t.series_years>266 AND t.production_year<1995 AND ci.role_id=2;,32572
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>751 AND t.phonetic_code<13566 AND t.production_year<2002 AND ci.role_id>2;,108929
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2013 AND t.series_years>175 AND t.phonetic_code<16253 AND ci.role_id>1;,8877
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<150 AND t.phonetic_code>22041 AND t.production_year<2011 AND ci.role_id=2;,10
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>6866 AND t.series_years<1157 AND t.production_year<1961 AND ci.role_id<2;,4597
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<493 AND t.phonetic_code<13603 AND t.production_year<2007 AND ci.role_id>2;,6226
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>22306 AND t.production_year<2011 AND t.series_years<505 AND ci.role_id<2;,105
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2009 AND t.series_years>909 AND t.phonetic_code<2567 AND ci.role_id=1;,4775
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<6860 AND t.production_year<2006 AND t.series_years<379 AND ci.role_id<2;,3992
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>653 AND t.production_year>2012 AND t.phonetic_code<270 AND ci.role_id=1;,47
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<596 AND t.production_year=2009 AND t.phonetic_code>2334 AND ci.role_id=1;,20
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2009 AND t.phonetic_code<16587 AND t.series_years<324 AND ci.role_id=1;,5392
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1974 AND t.series_years<646 AND t.phonetic_code<5364 AND ci.role_id>1;,11087
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<505 AND t.phonetic_code>5246 AND t.production_year<1987 AND ci.role_id=4;,2570
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2000 AND t.phonetic_code<10428 AND t.series_years=447 AND ci.role_id>4;,9
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=1150 AND t.production_year<2010 AND t.phonetic_code>8075 AND ci.role_id=2;,57
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<281 AND t.production_year<1979 AND t.phonetic_code>5558 AND ci.role_id=1;,3391
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>869 AND t.production_year<2010 AND t.phonetic_code>12325 AND ci.role_id=1;,78450
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>10615 AND t.series_years=1183 AND t.production_year<1998 AND ci.role_id=1;,78
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<2578 AND t.production_year>1986 AND t.series_years>762 AND ci.role_id=2;,23583
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1184 AND t.production_year<2012 AND t.phonetic_code<20345 AND ci.role_id>1;,380218
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<1158 AND t.production_year<2001 AND t.phonetic_code<8045 AND ci.role_id>1;,66310
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>216 AND t.production_year<1999 AND t.phonetic_code>1491 AND ci.role_id>1;,214572
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=837 AND t.production_year<2012 AND t.series_years>1023 AND ci.role_id>1;,9
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>259 AND t.phonetic_code>21957 AND t.production_year<2001 AND ci.role_id=1;,2460
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years<119 AND t.production_year>2011 AND t.phonetic_code>144 AND ci.role_id=2;,4
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code<20834 AND t.series_years=411 AND t.production_year<2007 AND ci.role_id>1;,2
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>3867 AND t.production_year=1985 AND t.series_years<640 AND ci.role_id=2;,23
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2004 AND t.series_years>395 AND t.phonetic_code>5149 AND ci.role_id=1;,133281
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>1024 AND t.phonetic_code>1599 AND t.production_year=2006 AND ci.role_id=1;,9708
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<1990 AND t.phonetic_code<11767 AND t.series_years<777 AND ci.role_id=1;,23680
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years=993 AND t.phonetic_code>8073 AND t.production_year<2010 AND ci.role_id>1;,15
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code=11932 AND t.production_year=2000 AND t.series_years>848 AND ci.role_id<2;,9
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year<2012 AND t.series_years>581 AND t.phonetic_code<12292 AND ci.role_id>2;,231525
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=1960 AND t.phonetic_code>20959 AND t.series_years<704 AND ci.role_id<2;,5
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year=2012 AND t.phonetic_code=16973 AND t.series_years>614 AND ci.role_id>1;,16
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.series_years>502 AND t.phonetic_code>1195 AND t.production_year<2011 AND ci.role_id=2;,144110
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.phonetic_code>2242 AND t.production_year>2002 AND t.series_years>1015 AND ci.role_id=1;,82714
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1997 AND t.phonetic_code>14687 AND t.series_years>686 AND ci.role_id=2;,28539
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1961 AND t.series_years>1197 AND t.phonetic_code=2778 AND ci.role_id>1;,37
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>1999 AND t.series_years=132 AND t.phonetic_code<16035 AND ci.role_id<2;,9
SELECT COUNT(*) FROM cast_info ci, title t WHERE t.id=ci.movie_id AND t.production_year>2009 AND t.series_years<589 AND t.phonetic_code>11360 AND ci.role_id=1;,70